# Generated by Django 3.0.6 on 2020-06-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20200624_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='back',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='balley_lose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='bitri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='cardio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='leg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='shoulder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='six_pack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_lose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='chest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
