# Generated by Django 3.0.6 on 2020-06-26 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_profile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('[0]{1}[3]{1}[0-9]{2}[-]{1}[0-9]{7}$')]),
        ),
    ]
