# Generated by Django 3.0.6 on 2020-07-04 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0006_auto_20200626_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('[0]{1}[3]{1}[0-9]{2}[-]{1}[0-9]{7}')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='gym/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
