# Generated by Django 3.0.8 on 2020-07-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Profile'),
        ),
    ]
