# Generated by Django 3.0.8 on 2020-08-25 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20200726_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('reguler_m', 'reguler_m'), ('reguler_f', 'reguler_f')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, default='0300-0000000', max_length=15, null=True, validators=[django.core.validators.RegexValidator('[0]{1}[3]{1}[0-9]{2}[-]{1}[0-9]{7}')]),
        ),
    ]
