# Generated by Django 3.0.8 on 2020-08-25 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_auto_20200825_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, default='03000000000', max_length=15, null=True, validators=[django.core.validators.RegexValidator('[0]{1}[3]{1}[0-7]{2}[0-9]{7}')]),
        ),
    ]
